version: '3.8'  # Versão mínima que suporta recursos usados

services:
  file-server:
    build:
      context: .  # Build usando Dockerfile no diretório atual
      dockerfile: Dockerfile.server  # Dockerfile específico para o servidor
    ports:
      - "5000:5000"  # Expõe a porta do servidor para o host (não necessário para comunicação entre containers)
    networks:
      - file_system_network  # Conecta à rede compartilhada

  # Clientes com configuração idêntica exceto pelo HOSTNAME
  file-client-1:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - HOSTNAME=file-client-1  # Usado pelo client.py para selecionar credenciais
      - SERVER_HOST=file-server  # DNS interno do Docker para o serviço do servidor
    depends_on:
      - file-server  # Garante ordem de inicialização (não saúde do serviço)
    networks:
      - file_system_network  # Mesma rede do servidor

  file-client-2:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - HOSTNAME=file-client-2
      - SERVER_HOST=file-server
    depends_on:
      - file-server
    networks:
      - file_system_network

  file-client-3:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - HOSTNAME=file-client-3
      - SERVER_HOST=file-server
    depends_on:
      - file-server
    networks:
      - file_system_network

networks:
  file_system_network:
    driver: bridge  # Rede isolada para comunicação entre serviços
